module.exports = {
  landingPage: {
    navLinks: [
      { label: "How it works", href: "#how" },
      { label: "Blood supply", href: "#inventory" },
      { label: "For blood banks", href: "admin-login.html" },
    ],
    heroAlert: "Live - O- blood at 8% nationally - donors urgently needed",
    heroTitle: "The right blood, at the right place, at the right time",
    heroLede:
      "BloodLine eliminates the chaos of emergency blood donation. No more 4-hour queues. Your blood type is matched to national need in real-time - and you're only called when it counts.",
    heroActions: [
      { label: "Login with Singpass", href: "user-home.html", tone: "primary", icon: "user" },
      { label: "Blood bank login", href: "admin-login.html", tone: "ghost" },
      { label: "Check blood supply", href: "#inventory", tone: "ghost", icon: "arrow-right" },
    ],
    stats: [
      { value: "8%", label: "O- national capacity" },
      { value: "5", label: "blood centres coordinated" },
      { value: "12,400", label: "registered donors" },
      { value: "20 min", label: "Fast-pass arrival window" },
    ],
    inventoryHeading: "National blood supply - right now",
    inventorySubheading: "Updated continuously from all HSA-linked blood banks across Singapore.",
    workflowHeading: "Coordinated, not chaotic",
    workflowSubheading: "A strict rule-based algorithm matches donors to need - no guesswork, no crowding.",
    steps: [
      {
        title: "Login via Singpass",
        body: "Your identity is verified instantly. Verification of blood type is needed.",
      },
      {
        title: "System checks your eligibility",
        body: "Travel history, donation interval, and blood type deficit are assessed in real time.",
      },
      {
        title: "Fast-Pass issued if critical",
        body: "If your blood type is at critical low, you're bumped to the top and issued a QR code.",
      },
      {
        title: "Arrive in your 20-min window",
        body: "Scan your QR at the centre, skip the queue, and donate when you're needed most.",
      },
    ],
    cta: {
      eyebrow: "Ready to donate?",
      title: "Singapore needs you.",
      body: "Login takes under 30 seconds. Your Fast-Pass is waiting.",
    },
    footer: "Built for Singapore - in partnership with HSA - Data sourced live from national blood banks",
  },
  ui: {
    date: "Tuesday, 20 May 2026",
    locale: "English",
  },
  donorProfile: {
    initials: "BT",
    name: "Bryan Tan",
    fullName: "Bryan Tan Wei Ming",
    id: "BL-20419",
    bloodType: "O-",
    age: 36,
    nric: "S****123A",
    dob: "14 Mar 1990",
    mobile: "+65 9754 6671",
    email: "bryantan@gmail.com",
    address: "Blk 412 Clementi Ave 1, #08-22, S120412",
    weight: "72kg",
    lastHb: "14.2 g/dL",
    lastHbMeta: "Recorded 4 Mar 2026 - by staff",
    donations: 12,
    points: 2400,
    nextEligible: "Today",
  },
  inventory: {
    public: [
      { type: "O-", status: "critical", pct: 8, label: "8% capacity" },
      { type: "A-", status: "low", pct: 22, label: "22% capacity" },
      { type: "B-", status: "low", pct: 28, label: "28% capacity" },
      { type: "AB-", status: "low", pct: 32, label: "32% capacity" },
      { type: "O+", status: "good", pct: 62, label: "62% capacity" },
      { type: "A+", status: "good", pct: 72, label: "72% capacity" },
      { type: "B+", status: "good", pct: 68, label: "68% capacity" },
      { type: "AB+", status: "good", pct: 76, label: "76% capacity" },
    ],
    admin: [
      { type: "O-", status: "critical", pct: 8, label: "Critical" },
      { type: "A-", status: "low", pct: 22, label: "Low" },
      { type: "B-", status: "low", pct: 28, label: "Low" },
      { type: "AB-", status: "low", pct: 32, label: "Low" },
      { type: "O+", status: "good", pct: 62, label: "Adequate" },
      { type: "A+", status: "good", pct: 72, label: "Adequate" },
      { type: "B+", status: "good", pct: 68, label: "Adequate" },
      { type: "AB+", status: "good", pct: 76, label: "Adequate" },
    ],
  },
  donorAppointments: [
    {
      date: "21",
      month: "MAY",
      title: "Bloodbank@One Punggol",
      type: "O-",
      status: "Fast-Pass",
      time: "10:30 - 10:50",
      meta: "Fast-Pass Window",
      state: "active",
    },
    {
      date: "04",
      month: "FEB",
      title: "Bloodbank@Dhoby Ghaut",
      type: "A+",
      status: "Done",
      time: "14:00",
      meta: "Completed",
      state: "done",
    },
    {
      date: "12",
      month: "NOV",
      title: "Bloodbank@Dhoby Ghaut",
      type: "B-",
      status: "Done",
      time: "13:00",
      meta: "Completed",
      state: "done",
    },
    {
      date: "22",
      month: "APR",
      title: "Bloodbank@Dhoby Ghaut",
      type: "O+",
      status: "Done",
      time: "10:00",
      meta: "Completed",
      state: "done",
    },
  ],
  donorContacts: [
    { name: "Amelia Tan", relation: "Wife", number: "98221475" },
    { name: "Eric Tan", relation: "Brother", number: "81624423" },
  ],
  donorTravel: [
    { country: "Indonesia", city: "Lombok", status: "Cleared", note: "Returned 18 Nov 2025", sub: "Cleared 18 Mar 2026" },
    { country: "Australia", city: "Sydney", status: "Cleared", note: "Returned 18 Aug 2024", sub: "Cleared 18 Dec 2024" },
  ],
  donorRewards: {
    vouchers: [
      { logo: "NTUC", name: "FairPrice", meta: "$5 e-voucher - 500 pts" },
      { logo: "Grab", name: "GrabFood", meta: "$5 e-voucher - 500 pts" },
      { logo: "CDC", name: "CDC vouchers", meta: "$10 govt voucher - 1000 pts" },
      { logo: "HSA", name: "Health screening", meta: "CHAS subsidised - 800 pts" },
    ],
    milestones: [
      { icon: "drop", name: "First drop", meta: "Completed 1st donation", status: "Earned" },
      { icon: "fire", name: "On a streak", meta: "Donated 3 times in a year", status: "Earned" },
      { icon: "star", name: "Decade honor", meta: "Donated for 10 years", status: "Earned" },
      { icon: "shield", name: "Crisis responder", meta: "Donate during a critical alert", status: "Locked" },
      { icon: "trophy", name: "Platinum donor", meta: "Reach Platinum tier", status: "Locked" },
    ],
  },
  adminDashboard: {
    centre: "Bloodbank@One Punggol",
    alert: {
      title: "CRITICAL ALERT",
      text: "O- blood is at 8% capacity nationally - 3 Fast-Passes auto-issued",
    },
    cards: [
      { label: "Active donors", value: "4812", trend: "+38 this year", tone: "up" },
      { label: "Fast-Passes issued", value: "3", trend: "O- critical trigger", tone: "crit" },
      { label: "Donations today", value: "127", trend: "+12 vs yesterday", tone: "up" },
      { label: "Queue waittime", value: "8min", trend: "+3 min surge", tone: "warn" },
    ],
    queue: [
      { initials: "BT", name: "Bryan Tan", blood: "O-", centre: "Westgate Tower", time: "10:30 - 10:50", badge: "Fast-Pass" },
      { initials: "RL", name: "Rachel Lim", blood: "O-", centre: "Dhoby Ghaut", time: "11:00 - 11:20", badge: "Fast-Pass" },
      { initials: "KN", name: "Kumar Nair", blood: "O-", centre: "Woodlands", time: "11:30 - 11:50", badge: "Fast-Pass" },
      { initials: "YC", name: "Yeo Cheng", blood: "A+", centre: "One Punggol", time: "14:00 - 14:20", badge: "Scheduled" },
    ],
    donorAppointments: [
      { time: "09:00", end: "09:20", name: "Benji Lim", blood: "B-", status: "Fast-Pass", tone: "critical" },
      { time: "10:00", end: "10:20", name: "Priya Lakshmanan", blood: "A+", status: "Scheduled", tone: "good" },
      { time: "11:00", end: "11:20", name: "James Wong", blood: "O+", status: "Scheduled", tone: "good" },
      { time: "13:00", end: "13:20", name: "Aisha Tan", blood: "O-", status: "Fast-Pass", tone: "critical" },
      { time: "14:00", end: "14:20", name: "Yeo Cheng", blood: "A+", status: "Scheduled", tone: "good" },
      { time: "15:30", end: "15:50", name: "Lin Mei Xin", blood: "O+", status: "Scheduled", tone: "good" },
    ],
    centres: [
      { name: "Bloodbank@HSA", tone: "critical" },
      { name: "Bloodbank@Woodlands", tone: "low" },
      { name: "Bloodbank@Dhoby Ghaut", tone: "good" },
      { name: "Bloodbank@Westgate Tower", tone: "good" },
      { name: "Bloodbank@One Punggol", tone: "good" },
    ],
    stockUnits: {
      "O-": 4,
      "A-": 11,
      "B-": 14,
      "AB-": 16,
      "O+": 31,
      "A+": 36,
      "B+": 34,
      "AB+": 38,
    },
  },
  userAppointmentsPage: {
    locationLabel: "Location",
    selectedCentre: "Bloodbank@One Punggol",
    options: [
      "Bloodbank@One Punggol",
      "Bloodbank@Dhoby Ghaut",
      "Bloodbank@Woodlands",
      "Bloodbank@HSA",
    ],
    availabilityLabel: "Pick Availability",
    fastPassLabel: "Fast Pass",
    dateLabel: "21 May 2026",
    timeRangeLabel: "10:30am - 10:50am",
    cancelLabel: "Cancel",
    confirmLabel: "Confirm",
  },
  adminLoginPage: {
    headline: "Blood Bank Staff Access",
    body: "Update blood inventory levels in real time. Your inputs directly affect national donor routing.",
    title: "Sign in",
    subtitle: "Select your blood centre and enter your password",
    centreLabel: "Blood centre",
    passwordLabel: "Password",
    submitLabel: "Sign in to admin portal",
    centres: [
      { name: "Bloodbank@HSA", tone: "critical" },
      { name: "Bloodbank@Woodlands", tone: "low" },
      { name: "Bloodbank@Dhoby Ghaut", tone: "good" },
      { name: "Bloodbank@Westgate Tower", tone: "good" },
      { name: "Bloodbank@One Punggol", tone: "good" },
    ],
  },
  adminDonorsPage: {
    centre: "Bloodbank@One Punggol",
    appointmentsOnlyLabel: "appointments only",
    heading: "Donors",
    dateLabel: "Tuesday, 20 May 2026",
    filterLabel: "Today - 20 May",
    appointmentsCount: 6,
    listTitle: "Today's appointments",
    listMeta: "6 donors - One Punggol",
    selected: {
      initials: "BL",
      name: "Benji Lim",
      bloodType: "B-",
      badge: "Fast-Pass",
      phone: "+65 9234 5678",
      email: "benjiLim@gmail.com",
      appointment: "09:00 - 09:20 - One Punggol",
      emergencyContacts: [
        { name: "Tan May Hua (Wife)", phone: "+65 8326 5995" },
        { name: "Celine Lim (Sister)", phone: "+65 9359 8233" },
      ],
    },
    appointments: [
      { time: "09:00", end: "09:20", name: "Benji Lim", blood: "B-", status: "Fast-Pass", tone: "critical", selected: true },
      { time: "10:00", end: "10:20", name: "Priya Lakshmanan", blood: "A+", status: "Scheduled", tone: "good" },
      { time: "11:00", end: "11:20", name: "James Wong", blood: "O+", status: "Scheduled", tone: "good" },
      { time: "13:00", end: "13:20", name: "Aisha Tan", blood: "O-", status: "Fast-Pass", tone: "critical" },
      { time: "14:00", end: "14:20", name: "Yeo Cheng", blood: "A+", status: "Scheduled", tone: "good" },
      { time: "15:30", end: "15:50", name: "Lin Mei Xin", blood: "O+", status: "Scheduled", tone: "good" },
    ],
  },
  adminBloodCentresPage: {
    heading: "Blood Centres",
    locationLabel: "Bloodbank@One Punggol",
    inventoryLabel: "inventory",
    updatedLabel: "Last Updated: Today, 09:42",
    saveLabel: "Save Changes",
    centre: {
      name: "Bloodbank@One Punggol",
      address: "1 Punggol Drive, #02-38 - Open: 08:00 - 17:00",
      totalUnits: 184,
      criticalTypes: 1,
      lowTypes: 3,
    },
    note: "Changes are reflected nationally once saved. Threshold: Critical <15%, Low <40%.",
  },
};
